
import java.sql.PreparedStatement;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jude
 */

public class ListGuard extends javax.swing.JFrame {
    java.sql.Connection conn = null;
    java.sql.Statement s;
    java.sql.ResultSet r;
DefaultTableModel tb1;

    /**
     * Creates new form ListGuard
     */
    public ListGuard() {
        tb1 = (DefaultTableModel)jTable1.getModel();
        initComponents();
        initialize();
        display();
        try {
            s = conn.createStatement();
            r = s.executeQuery("SELECT * FROM product");
            ResultSetMetaData j = r.getMetaData();
        } catch (Exception e) {
        }
    }
public void initialize() {
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            conn = java.sql.DriverManager.getConnection(
                    "jdbc:mysql://localhost/PrisonBreak?user=root&password=root");

        } catch (Exception e) {
            System.out.println(e);
            //System.exit(0);
        }
}

public void display(){
     try {
            if (r.isLast()) {
                JOptionPane.showMessageDialog(null, "No More products in Database");
            }
           while(r.next()){
            tb1.addRow(new Object[]{r.getString("guard_id"), r.getString("first_name"), r.getString("last_name"), r.getString("gender"),r.getString("year_of_employment")});
           }
        } catch (SQLException ex) {
        }
    }                             

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Guard ID", "First Name", "Last Name", "Gender", "Year of Employment", "Shift Begin", "Shift End"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Return");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 709, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
DefaultTableModel record;

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     editGuard();   // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
public void editGuard(){
//      record = (DefaultTableModel) jTable1.getModel();

        int row = jTable1.getSelectedRow();
        int column = jTable1.getSelectedColumn();
        int code = column - column;
        int dataCode = Integer.parseInt((String) jTable1.getValueAt(row, code));

        if (column == 1) {
            String msg = JOptionPane.showInputDialog(null, "Please Enter First Name:");
            try {
                PreparedStatement p = conn.prepareStatement("UPDATE prisoners SET First Name=? WHERE Code=?;");
                p.setString(1, msg);
                p.setInt(2, dataCode);
                p.execute();
                jTable1.setValueAt(msg, row, column);
            } catch (Exception e) {
                System.out.println("Error" + e.toString());
                return;
            }
        } else if (column == 2) {
            String msg = JOptionPane.showInputDialog(null, "Please Enter Last Name :");
            try {
                PreparedStatement p = conn.prepareStatement("UPDATE prisoners SET Last Name=? WHERE Code=?;");
                p.setString(1, msg);
                p.setInt(2, dataCode);
                p.execute();
                jTable1.setValueAt(msg, row, column);
            } catch (Exception e) {
                System.out.println("Error" + e.toString());
                return;
            }
        } else if (column == 3) {
            String[] list = {"m", "f"};
            String msg = (String) JOptionPane.showInputDialog(null, "Choose Gender", "Nice", JOptionPane.QUESTION_MESSAGE, null, list, list[0]);
            try {
                PreparedStatement p = conn.prepareStatement("UPDATE prisoners SET Gender=? WHERE Code=?;");
                p.setString(1, msg);
                p.setInt(2, dataCode);
                p.execute();
                jTable1.setValueAt(msg, row, column);
            } catch (Exception e) {
                System.out.println("Error" + e.toString());
                return;
            }
        }else if (column == 4) {
            String msg = JOptionPane.showInputDialog(null, "Please Enter Year of Employment :");
            try {
                PreparedStatement p = conn.prepareStatement("UPDATE prisoners SET Year of Employment=? WHERE Code=?;");
                p.setInt(1, Integer.parseInt(msg));
                p.setInt(2, dataCode);
                p.execute();
                jTable1.setValueAt(msg, row, column);
            } catch (Exception e) {
                System.out.println("Error" + e.toString());
                return;
            }
        }else if (column == 5) {
            String msg = JOptionPane.showInputDialog(null, "Please Enter Shift Begin:");
            try {
                PreparedStatement p = conn.prepareStatement("UPDATE prisoners SET Shift Begin=? WHERE Code=?;");
                p.setInt(1, Integer.parseInt(msg));
                p.setInt(2, dataCode);
                p.execute();
                jTable1.setValueAt(msg, row, column);
            } catch (Exception e) {
                System.out.println("Error" + e.toString());
                return;
            }
        }else if (column == 6) {
            String msg = JOptionPane.showInputDialog(null, "Please Enter Shift End:");
            try {
                PreparedStatement p = conn.prepareStatement("UPDATE prisoners SET Shift End=? WHERE Code=?;");
                p.setInt(1, Integer.parseInt(msg));
                p.setInt(2, dataCode);
                p.execute();
                jTable1.setValueAt(msg, row, column);
            } catch (Exception e) {
                System.out.println("Error" + e.toString());
                return;
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListGuard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListGuard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListGuard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListGuard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListGuard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
